/*
 * generated by Xtext 2.19.0
 */
package ru.iaie.reflex


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ReflexRuntimeModule extends AbstractReflexRuntimeModule {
}
