/*
 * generated by Xtext 2.19.0
 */
package ru.iaie.reflex


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ReflexStandaloneSetup extends ReflexStandaloneSetupGenerated {

	def static void doSetup() {
		new ReflexStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
