/*
 * generated by Xtext 2.19.0
 */
package ru.iaie.reflex.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import ru.iaie.reflex.ReflexRuntimeModule
import ru.iaie.reflex.ReflexStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class ReflexIdeSetup extends ReflexStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new ReflexRuntimeModule, new ReflexIdeModule))
	}
	
}
