/**
 * generated by Xtext 2.19.0
 */
package ru.iaie.reflex.reflex;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Register</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ru.iaie.reflex.reflex.Register#getType <em>Type</em>}</li>
 *   <li>{@link ru.iaie.reflex.reflex.Register#getName <em>Name</em>}</li>
 *   <li>{@link ru.iaie.reflex.reflex.Register#getAddr1 <em>Addr1</em>}</li>
 *   <li>{@link ru.iaie.reflex.reflex.Register#getAddr2 <em>Addr2</em>}</li>
 *   <li>{@link ru.iaie.reflex.reflex.Register#getRegSize <em>Reg Size</em>}</li>
 * </ul>
 *
 * @see ru.iaie.reflex.reflex.ReflexPackage#getRegister()
 * @model
 * @generated
 */
public interface Register extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link ru.iaie.reflex.reflex.RegisterType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see ru.iaie.reflex.reflex.RegisterType
   * @see #setType(RegisterType)
   * @see ru.iaie.reflex.reflex.ReflexPackage#getRegister_Type()
   * @model
   * @generated
   */
  RegisterType getType();

  /**
   * Sets the value of the '{@link ru.iaie.reflex.reflex.Register#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see ru.iaie.reflex.reflex.RegisterType
   * @see #getType()
   * @generated
   */
  void setType(RegisterType value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ru.iaie.reflex.reflex.ReflexPackage#getRegister_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ru.iaie.reflex.reflex.Register#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Addr1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Addr1</em>' attribute.
   * @see #setAddr1(int)
   * @see ru.iaie.reflex.reflex.ReflexPackage#getRegister_Addr1()
   * @model
   * @generated
   */
  int getAddr1();

  /**
   * Sets the value of the '{@link ru.iaie.reflex.reflex.Register#getAddr1 <em>Addr1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Addr1</em>' attribute.
   * @see #getAddr1()
   * @generated
   */
  void setAddr1(int value);

  /**
   * Returns the value of the '<em><b>Addr2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Addr2</em>' attribute.
   * @see #setAddr2(int)
   * @see ru.iaie.reflex.reflex.ReflexPackage#getRegister_Addr2()
   * @model
   * @generated
   */
  int getAddr2();

  /**
   * Sets the value of the '{@link ru.iaie.reflex.reflex.Register#getAddr2 <em>Addr2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Addr2</em>' attribute.
   * @see #getAddr2()
   * @generated
   */
  void setAddr2(int value);

  /**
   * Returns the value of the '<em><b>Reg Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reg Size</em>' attribute.
   * @see #setRegSize(int)
   * @see ru.iaie.reflex.reflex.ReflexPackage#getRegister_RegSize()
   * @model
   * @generated
   */
  int getRegSize();

  /**
   * Sets the value of the '{@link ru.iaie.reflex.reflex.Register#getRegSize <em>Reg Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reg Size</em>' attribute.
   * @see #getRegSize()
   * @generated
   */
  void setRegSize(int value);

} // Register
