/*
 * generated by Xtext 2.19.0
 */
package ru.iaie.reflex.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractReflexScopeProvider extends DelegatingScopeProvider {
}
